name: lint-wf
on:
  push:
    branches:
      - develop
  pull_requests:
    branches:
      - develop
jobs:
  linting-jobs:
    runs-on: ub ubuntu-latest
    steps:
      - name: clone Repository
        uses: actions/checkout@v4
      - name: Install HTMLHint
        run: npm install --save-dev htmlhint
      - name: Lint HTML Files
        run: npx htmlhint "**/*.html"
      - name: Install Stylelint 
        run: npm install --save-dev stylelint 
      - name: lint CSS Files
        run: npx stylelint "**/css"
      - name: Display Package.json Contents
        run: cat package.json